log:
  filepath: logs
  filename: system.log
system:
#  环境
  Mode: release
#  秘钥
  Secret: d3a5c5c29c1130bddf55b8cda7ac770b9c085f0fe0b1c1ce3c566b90c78769d4
#  rsa私钥
  RSAPrivate: config/rsa/private.pem
#  rsa公钥
  RSAPublic: config/rsa/public.pem
#  过期时间（秒）
  TokenExpireTime: 3600
  RedisExpireTime: 3600
  SessionExpireTime: 86400
#  设备ID
  WorkerID: 00000
#  数据中心ID
  DataCenterID: 00000
#  fs本地文件系统路径
  FsPath: fs
#  部署服务器ip
  SysIP: 127.0.0.1
#  部署服务器端口
  SysPort: 9011
#  使用mysql
  UseMysql: true
#  使用redis
  UseRedis: false